name: weatherapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  numberpicker: ^2.1.1
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.0.1
  package_info_plus: ^3.0.2 # Add this line



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
dependency_overrides:
  win32: ^5.7.0
